name: FatTnt
main: me.asofold.bukkit.fattnt.FatTnt
version: 0.1.8-DEV
commands:
  fattnt:
    description: 'Reload, enable, disable etc.'
    usage: '/fattnt reload | /fattnt enable | /fattnt disable | /fattnt stats | /fattnt stats reset |'
    aliases:
    - ftnt